### ISSUE TITLE
Add create endpoint action

### ISSUE THREAD

**Issue by christophd** [citrusframework/citrus#1360]
Users may use dynamic endpoints in a test such as

```yaml
- send:
    endpoint: "kafka:foo-topic?server=${kafka.bootstrapServer}"
# ...
- receive:
    endpoint: "kafka:foo-topic?server=${kafka.bootstrapServer}"
# ...
```

The dynamic endpoint receives all connection properties in its endpoint URI. Instead of having to redeclare the same properties over and over again we should introduce a create-endpoint test action that defines the dynamic endpoint and gives it a name. Follow up test action may reference the endpoint as usual by its given name.

```yaml
- createEndpoint:
    name: "foo"
    uri: "kafka:foo-topic?server=${kafka.bootstrapServer}"
- send:
    endpoint: "foo"
# ...
- receive:
    endpoint: "foo"
# ...
```

As an alternative syntax endpoints may declare the properties as follows:

```yaml
- createEndpoint:
    name: "foo"
    type: "kafka"
    properties:
      topicName: foo-topic
      server: "${kafka.bootstrapServer}"
```
